package repaso;

public enum Genero {
    ACCIÓN,AVENTURA,COMEDIA,DRAMA,TERROR,CIENCIAFICCIÓN,FANTASÍA,SUSPENSO,ROMANCE,ANIMACIÓN,DOCUMENTAL,MUSICAL,CRIMEN,MISTERIO,BÉLICA,HISTÓRICA,DEPORTIVA,FAMILIAR,BIOGRÁFICA,WESTERN,CORTOMETRAJE,NOIR,THRILLER,EXPERIMENTAL
}
