package TiendaProductosElectronicos;

public enum Seccion {
    MULTIMEDIA,COCINA,LAVADO,CLIMATIZACION,PEQUEÑOS,ELECTRONICA,ILUMINACION,HERRAMIENTAS,ACCESORIOS,COMPUTACION,SEGURIDAD,REDES,SONIDO,VIDEO,JARDIN,OFICINA,DOMOTICA,SALUD,BEBIDAS,CAFETERAS,CLIMATIZACIONINDUSTRIAL,REFRIGERACION,CALEFACCION,TELEFONIA
}
